mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('servisas/', include('servisas.urls')),
    path('', RedirectView.as_view(url='servisas/', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')),
    path('tinymce/', include('tinymce.urls')),
] + (static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) +
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

mysite/servisas/urls.py
from django.urls import path, include
from . import views


urlpatterns = [
    path("", views.index, name="index"),
    path('automobiliai/', views.automobiliai, name='automobiliai'),
    path('automobiliai/<int:automobilis_id>', views.automobilis, name='automobilis'),

    path('uzsakymai/', views.UzsakymaiListView.as_view(), name='uzsakymai'),
    path('uzsakymai/<int:pk>', views.UzsakymasDetailView.as_view(), name="uzsakymas"),# o gal vis delto uzsakymas
    path('search/', views.search, name='search'),
    path("vartotojouzsakymai/", views.VartotojoUzsakymasListView.as_view(), name="vartotojo_uzsakymai"),
    path('register/', views.register, name='register'),
    path('profilis/', views.profilis, name='profilis'),

    path('vartotojouzsakymai/<int:pk>', views.UzsakymaiVartotojoDetailView.as_view(), name='vartotojo-uzsakymai'),

    path('uzsakymai/sukurti', views.UzsakymaiVartotojoCreateView.as_view(), name='sukurti-nauja'),
    path('uzsakymai/<int:pk>/redaguoti', views.UzsakymaiVartotojoUpdateView.as_view(), name='redaguoti-uzsakyma'),
    path('uzsakymai/<int:pk>/trinti', views.UzsakymaiVartotojoDeleteView.as_view(), name='trinti-uzsakyma'),
    path('i18n/', include('django.conf.urls.i18n')),
    path("uzsakymai/<int:uzsakymas_pk>/redaguotieilute/<int:pk>", views.UzsakymoEiluteUpdateView.as_view(), name="uzsakymas_redaguotieilute"),
    path("uzsakymai/<int:uzsakymas_pk>/istrintieilute/<int:pk>", views.UzsakymoEiluteDeleteView.as_view(), name="uzsakymas_istrintieilute"),
    path("uzsakymai/<int:pk>/pridetieilute", views.UzsakymoEiluteCreateView.as_view(), name="uzsakymas_pridetieilute"),
]

mysite/servisas/models.py
import uuid

from django.contrib.auth import get_user_model
from django.db import models

# Create your models here.
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from datetime import date, datetime
import pytz
from tinymce.models import HTMLField
from PIL import Image
from django.utils.translation import gettext_lazy as _

utc = pytz.UTC

class AutomobilioModelis(models.Model):
    marke = models.CharField(verbose_name=_('make'), max_length=80, help_text='Įveskite automobilio markę')
    modelis = models.CharField(_('model'), max_length=80, help_text='Įveskite automobilio modelį')

    def __str__(self):
        return f"{self.marke} {self.modelis}"

    class Meta:
        verbose_name = _("Car model") # atvaizduojams pavadinimas vienaskaita
        verbose_name_plural = _("Car models")# kad atvaizudotu teisingai daugiskaita


class Automobilis(models.Model):
    valstybinis_nr = models.CharField(verbose_name='Valstybiniai numeriai', max_length=10, help_text='Įveskite valstybinį numerį ')
    automobilio_modelis = models.ForeignKey(to='AutomobilioModelis', on_delete=models.SET_NULL, null=True)
    vin_kodas = models.CharField(verbose_name='VIN kodas', max_length=17, help_text='Įveskite 17 skaitmenų kodą ')
    klientas = models.CharField(verbose_name='Klientas', max_length=80, help_text='Įveskite vardą ')
    #description = models.TextField(verbose_name="Aprašymas", max_length=3000, blank=True, default="")
    virselis = models.ImageField('Viršelis', upload_to='covers', null=True)
    description = HTMLField(verbose_name="Aprašymas", blank=True, null=True)

    def __str__(self):
        return f"{self.automobilio_modelis} ({self.valstybinis_nr})"

    # def get_absolute_url(self):
    #     """Nurodo konkretaus aprašymo galinį adresą"""
    #     return reverse('book-detail', args=[str(self.id)])

    class Meta:
        verbose_name = _('Car')
        verbose_name_plural = _('Cars')

class Uzsakymas(models.Model):
    """Modelis, aprašantis automobilių taisymo užsakymus"""
    #id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unikalus ID')
    data = models.DateTimeField(verbose_name=_('Date'), auto_now_add=True, max_length=20, help_text='Užsakymo data?')
    automobilis = models.ForeignKey(to="Automobilis", verbose_name=_('Car'), on_delete=models.SET_NULL, null=True, blank=True)
    terminas = models.DateTimeField(verbose_name=_('Due back:'), null=True, blank=True)
    vartotojas = models.ForeignKey(User, verbose_name=_("User"), on_delete=models.SET_NULL, null=True, blank=True)

    # def baigesi_laikas(self):
    #     if self.terminas:
    #         return self.terminas < datetime.today()
    #     else:
    #         return False
    # def baigesi_laikas(self):
    #     if self.terminas and datetime.today() > self.terminas:
    #         return True
    #     return False
    def baigesi_laikas(self):
        if self.terminas:
            return self.terminas.replace(tzinfo=utc) < datetime.today().replace(tzinfo=utc)
        else:
            return False


    LOAN_STATUS = (
        ('p', _('Confirmed')),
        ('v', _('In Progress')),
        ('a', _('Cancelled')),
        ('i', _('Done')),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='p',
        help_text=_('Status'),
    )

    def suma(self):
        suma = 0
        eilutes = self.eilutes.all()
        for eilute in eilutes:
            suma += eilute.kaina()
        return suma

    def __str__(self):
        return f"{self.automobilis} ({self.terminas})"

    class Meta:
        verbose_name = _("Order")
        verbose_name_plural = _("Orders")


class Paslauga(models.Model):
    """Modelis aprašo serviso teikiamas paslaugas"""
    pavadinimas = models.CharField(verbose_name=_('Service title'), max_length=100, help_text='Įveskite paslaugos pavadinimą ')
    kaina = models.FloatField(verbose_name=_('Service cost'), max_length=20)

    def __str__(self):
        return f"{self.pavadinimas}"

    class Meta:
        verbose_name = _('Service')
        verbose_name_plural = _('Services')

class Uzsakymo_eilute(models.Model):
    paslauga = models.ForeignKey(to='Paslauga', verbose_name=_('Service'), on_delete=models.SET_NULL, null=True)
    uzsakymas = models.ForeignKey(to='Uzsakymas', verbose_name=_('Order'), on_delete=models.CASCADE, related_name="eilutes") #related tam, kad suma paskaiciuoti
    kiekis = models.IntegerField(verbose_name=_('Amount'))

    def kaina(self):
        return self.paslauga.kaina * self.kiekis

    def __str__(self):
        return f"{self.uzsakymas.data}, {self.paslauga} ({self.kiekis})"

    class Meta:
        verbose_name = _('Orderline')
        verbose_name_plural = _('Orderlines')

class UzsakymoApzvalga(models.Model):
    uzsakymas = models.ForeignKey(Uzsakymas, verbose_name=_('Order'), on_delete=models.SET_NULL, null=True, blank=True, related_name='atsiliepimai')
    vartotojas = models.ForeignKey(get_user_model(), verbose_name=_('User'), on_delete=models.SET_NULL, null=True, blank=True, related_name='vartotojas')
    date_created = models.DateTimeField('Sukūrimo data', auto_now_add=True)
    atsiliepimas = models.TextField('Atsiliepimas', max_length=2000) #nepadeda jei istrinu

    class Meta:
        verbose_name = _("Comment")
        verbose_name_plural = _('Comments')
        ordering = ['-date_created']

    def __str__(self) -> str:
        return f"{self.vartotojas} on {self.uzsakymas} at {self.date_created}"

class Profilis(models.Model):
    user = models.OneToOneField(User, verbose_name=_('User'), on_delete=models.CASCADE)
    foto = models.ImageField(default="default.png", verbose_name=_('Photo'), upload_to="profile_pics")

    class Meta:
        verbose_name = _("Profile")
        verbose_name_plural = _('Profiles')

    def __str__(self):
        return f"{self.user.username} profilis"

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.foto.path)
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.foto.path)

mysite/servisas/forms.py
from django.forms import DateInput

from .models import UzsakymoApzvalga, Profilis, Uzsakymas
from django import forms
from django.contrib.auth.models import User

class UzsakymoApzvalgaForm(forms.ModelForm):
    class Meta:
        model = UzsakymoApzvalga
        fields = ('uzsakymas', 'vartotojas', 'atsiliepimas') # ir cia istrynus, dingsta visa forma
        widgets = {'uzsakymas': forms.HiddenInput(), 'vartotojas': forms.HiddenInput()}

class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']

class ProfilisUpdateForm(forms.ModelForm):
    class Meta:
        model = Profilis
        fields = ['foto']


class ManoDateTimeInput(forms.DateTimeInput):
    input_type = 'datetime-local'

class UzsakymaiVartotojoCreateUpdateForm(forms.ModelForm):
    class Meta:
        model = Uzsakymas
        fields = ['automobilis', 'terminas', 'status']
        widgets = {'terminas': ManoDateTimeInput()}

mysite/servisas/templates/automobilis.html
{% extends "base.html" %}

{% block title %}Automobilis{% endblock %}

{% block content %}
{% load static %}

<div class="col-md-4 d-flex align-items-stretch">
<div class="card mb-4 shadow-sm">
{% if automobilis.virselis %}
  <img src="{{ automobilis.virselis.url }}" class="card-img-top" alt="...">
{% else %}
  <img src="{% static 'img/no-image.png' %}" class="card-img-top">
{% endif %}

<div class="card-body">
<h1>Automobilio duomenys:</h1>
<p>Klientas: {{ automobilis.klientas }}</p>
<p>Modelis: {{ automobilis.automobilio_modelis }}</p>
<p>Valstybinis nr: {{ automobilis.valstybinis_nr }}</p>
<p>VIN kodas: {{ automobilis.vin_kodas }}</p>
        </div>
    </div>
</div>

<hr>
<p>{{ automobilis.description | safe }}</p>
<hr>
</br>

<ol>
{% for automobilis in automobilis.modelis.all %}
    <li>{{ automobilis.title }}</li>
{% endfor %}
</ol>
{% endblock %}

mysite/servisas/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>{% block title %}{% endblock %}</title>
  <meta charset="utf-8">
    {% load static %}
  <link rel="stylesheet" href="{% static 'styles.css' %}">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>

<!--navigacija-->
{% load i18n %}
<nav class="navbar navbar-expand-lg navbar-light bg-light static-top mb-5 shadow">
  <div class="container">
    <a class="navbar-brand" href="#"><img src="{% static 'pipiras.png'%}">{% trans "Pepper Autoservice" %}</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
    </button>
<div class="collapse navbar-collapse" id="navbarResponsive">
    <ul class="navbar-nav ms-auto">
        <li class="nav-item"><a class="nav-link" href="{% url 'index' %}">{% trans "Home" %}</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'automobiliai' %}">{% trans "Cars" %}</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'uzsakymai' %}">{% trans "Orders" %}</a></li>


        {% if user.is_authenticated %}
        <li class="nav-item"><a class="nav-link" href="{% url 'profilis' %}">
            <svg class="bi bi-person" width="1.5em" height="1.5em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M13 14s1 0 1-1-1-4-6-4-6 3-6 4 1 1 1 1h10zm-9.995-.944v-.002.002zM3.022 13h9.956a.274.274 0 00.014-.002l.008-.002c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664a1.05 1.05 0 00.022.004zm9.974.056v-.002.002zM8 7a2 2 0 100-4 2 2 0 000 4zm3-2a3 3 0 11-6 0 3 3 0 016 0z" clip-rule="evenodd"/>
            </svg>
        {{ user.get_username }}</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'vartotojo_uzsakymai'%}">{% trans "My Orders" %}</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'sukurti-nauja'%}">{% trans "New Order" %}</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">{% trans "Logout" %}</a></li>
        {% else %}
        <li class="nav-item"><a class="nav-link" href="{% url 'register' %}">{% trans "Register"%}</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'login' %}">{% trans "Login" %}</a></li>
        {% endif %}
        <li>
            <form action="{% url 'search' %}" method="get" class="form-inline my-2 my-md-0">
            <input name="query" class="form-control" type="text" placeholder="{% trans 'Search' %}">
            </form>
        </li>

              <form action="{% url 'set_language' %}" method="post">
        {% csrf_token %}
        <input name="next" type="hidden" value="{{ redirect_to }}"/>
        <select name="language" onchange="this.form.submit()">
          {% load static %}
          {% get_current_language as LANGUAGE_CODE %}
          {% get_available_languages as LANGUAGES %}
          {% for lang in LANGUAGES %}
          <option style="background-image: url({% static 'img/lt.png' %});" value="{{ lang.0 }}" {% if lang.0 == LANGUAGE_CODE %} selected="selected" {% endif %}>
            {{ lang.1 }}
          </option>
          {% endfor %}
        </select>
      </form>
      </ul>
    </div>
  </div>
</nav>
<div>
  {% if messages %}
      {% for message in messages %}
          <div class="alert alert-{% if message.tags == 'error' %}danger{% elif message.tags == 'info' %}success{% endif %}" role="alert">
                  {{ message }}
          </div>
      {% endfor %}
  {% endif %}
</div>



<div class="col-sm-8">
{% block content %}{% endblock %}
</div>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
<!-- laikinai isimu
<footer class="fixed-bottom">
  <div class="mt-1 p-1 bg-light text-dark text-center">
    <p>ĮI "Pipirai", 2023</p>
  </div>
</footer>
-->
</body>
</html>

mysite/servisas/templates/index.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}HOME{% endblock %}

{% block content %}
<!--<h1>Autoservisas</h1>-->
<h3><i>{% trans "Welcome to 'Pipiro' autoservice!" %}</i></h3>
<br><b>{% trans "Our service statistics:" %}</b><br>

<ul>
    <li><b>{% trans "Services already provided:" %}</b> {{ num_paslaugu }}</li>
    <li><b>{% trans "Orders fulfilled:" %}</b> {{ num_uzsakymai }}</li>
    <li><b>{% trans "Cars/Customers Serviced:" %}</b> {{ num_automobiliai }}</li>
</ul>
<p> {% trans "Your visits: "%}{{ num_apsilankymai }}</p>
{% endblock %}

mysite/servisas/templates/profilis.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
      <div class="content-section">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-danger" role="alert">
            {{ message }}
        </div>
        {% endfor %}
        {% endif %}

      <div class="media">
        <img class="rounded-circle account-img" src="{{ user.profilis.foto.url }}">
        <div class="media-body">
          <h2 class="account-heading">{{ user.username }}</h2>
          <p class="text-secondary">{{ user.email }}</p>
        </div>
      </div>
       <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Profilio info:</legend>
                {{ u_form|crispy }}
                {{ p_form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Atnaujinti</button>
            </div>
        </form>
    </div>
{% endblock content %}

mysite/servisas/templates/search.html
{% extends "base.html" %}

{% block content %}
  <h1>Paieškos pagal "{{query}}" rezultatai:</h1>
  </br>
  {% if automobiliai %}
  <ul>
    {% for automobilis in automobiliai %}
      <li>
        <a href="{{ automobilis.id }}">{{ automobilis.automobilio_modelis }}</a> ({{automobilis.klientas}})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>Rezultatų nerasta :(</p>
  {% endif %}

  {% endblock %}

mysite/servisas/templates/uzsakymai.html
{% extends "base.html" %}

{% block title %}Visi užsakymai{% endblock %}

{% block content %}
<h1>Užsakymai:</h1>
{% if uzsakymai %}
{% for uzsakymas in uzsakymai %}
<hr>
        <img class="rounded-circle" src="{{uzsakymas.vartotojas.profilis.foto.url}}">
        <a href="{% url 'uzsakymas' uzsakymas.pk %}">{{uzsakymas}}</a>

{% endfor %}
{% endif %}

 <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; pirmas</a>
            <a href="?page={{ page_obj.previous_page_number }}">atgal</a>
        {% endif %}

        <span class="current">
            {{ page_obj.number }} iš {{ page_obj.paginator.num_pages }}
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">pirmyn</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">paskutinis &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock %}

mysite/servisas/templates/uzsakymas.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans "Order Detail View" %}{% endblock %}

{% block content %}

<h4>{% trans "Order number:" %} {{ uzsakymas.id }}</h4>
<p><b>{% trans "Client:" %} </b>{{ uzsakymas.automobilis.klientas}}</p>
<p><b>{% trans "Licence plate number:" %} </b>{{ uzsakymas.automobilis.valstybinis_nr }}</p>
<p><b>{% trans "Order date:" %} </b>{{ uzsakymas.data }}</p>
<p><b>{% trans "Due back:" %} </b>{{ uzsakymas.terminas }}</p>
<p><b>{% trans "User:" %} </b>{{ uzsakymas.vartotojas }}</p>
<p><b>{% trans "Status:" %} </b>{{ uzsakymas.get_status_display }}</p>
<hr>
{% if uzsakymas.vartotojas == user %}
<div>
    <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'redaguoti-uzsakyma' uzsakymas.id %}">{% trans "Edit:" %}</a>
    <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'trinti-uzsakyma' uzsakymas.id %}">{% trans "Delete:" %}</a>
</div>
{% endif %}

<table class="table table-hover">
  <thead>
    <tr class="table-info">
      <th scope="col">{% trans "Service title:" %}</th>
      <th scope="col">{% trans "Amount:" %}</th>
      <th scope="col">{% trans "Price:" %}</th>
      <th scope="col">{% trans "Sum:" %}</th>
      {% if uzsakymas.vartotojas == user %}
      <th scope="col"></th>
      {% endif%}
    </tr>

  </thead>
  <tbody>
  {% for eilute in uzsakymas.eilutes.all %}
    <tr>
      <th scope="row">{{eilute.paslauga.pavadinimas}}</th>
      <td>{{eilute.kiekis}}</td>
      <td>{{eilute.paslauga.kaina}}</td>
      <td>{{eilute.kaina}}</td>
      {% if uzsakymas.vartotojas == user %}
       <td scope="row">
           <div>
                <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'uzsakymas_redaguotieilute' uzsakymas.id eilute.id %}">{% trans "Edit:" %}</a>
                <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'uzsakymas_istrintieilute' uzsakymas.id eilute.id %}">{% trans "Delete:" %}</a>
            </div>
        </td>
       {% endif %}
    </tr>
  {% endfor %}
  <tr class="table-active">
      <td colspan="3"><i><b>{% trans "TOTAL:" %}</b></i></td>
      <th><i>{{uzsakymas.suma}}</i></th>
  </tr>
  </tbody>
</table>
{% if uzsakymas.vartotojas == user %}
<div>
    <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'uzsakymas_pridetieilute' uzsakymas.id %}">{% trans "Add line:" %}</a>
</div>
{% endif %}
<br/>
<h4>{% trans "Comments:" %}</h4>
{% if uzsakymas.atsiliepimai.all %}
{% for atsiliepimas in uzsakymas.atsiliepimai.all %}
      <hr>
      <strong>{{ atsiliepimas.vartotojas }}</strong>, <em>{{ atsiliepimas.date_created}}</em>
      <p>{{ atsiliepimas.atsiliepimas }}</p>
    {% endfor %}
  {% else %}
    <p>{% trans "No Comments Yet" %}</p>
  {% endif %}
{% if user.is_authenticated %}
<div class="fieldWrapper">
    <hr>
    <h4>{% trans "Leave a Comment:" %}</h4>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="{% trans 'Send' %}">
    </form>
</div>
{% endif %}
{% endblock %}

mysite/servisas/templates/uzsakymoeilute_delete.html
{% extends "base.html" %}
{% block title %}Užsakymo eilutės trynimas{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Ištrinti užsakymo eilutę</legend>
            <h2>Ar tikrai ištrinti užsakymo eilutę {{ uzsakymoeilute }}?</h2>
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-danger" type="submit">Taip, ištrinti</button>
            <a class="btn btn-outline-secondary" href="{% url 'uzsakymas' uzsakymoeilute.uzsakymas.id %}">Atšaukti</a>
        </div>
    </form>
    </div>
{% endblock content %}

mysite/servisas/templates/uzsakymoeilute_form.html
{% extends "base.html" %}
{% block title %}Pridėti/redaguoti užsakymo eilutę{% endblock %}
{% block content %}
{% load crispy_forms_tags %}
    <div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Pridėti/redaguoti užsakymo eilutę</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Išsaugoti</button>
        </div>
    </form>
    </div>
{% endblock content %}

mysite/servisas/templates/vartotjo_uzsakymas_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Naujas užsakymas</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Išsaugoti</button>
        </div>
    </form>
    </div>
{% endblock content %}

mysite/servisas/templates/vartotojo_uzsakymai.html
{% extends "base.html" %}

{% block title %}Mano užsakymai{% endblock %}

{% block content %}
<h1>Mano užsakymai:</h1>
{% if uzsakymai %}
{% for uzsakymas in uzsakymai %}
<hr>
    <img class="rounded-circle" src="{{uzsakymas.automobilis.virselis.url}}">
    <a href="{% url 'uzsakymas' uzsakymas.pk %}">
     <p class="{% if uzsakymas.baigesi_laikas %}text-danger{% endif %}">{{ uzsakymas }}</p>
    <br/>

    </a>
    {% endfor %}
    {% else %}
    <p>Užsakymų nerasta.</p>
{% endif %}

 <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; pirmas</a>
            <a href="?page={{ page_obj.previous_page_number }}">atgal</a>
        {% endif %}

        <span class="current">
            {{ page_obj.number }} iš {{ page_obj.paginator.num_pages }}
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">pirmyn</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">paskutinis &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock %}